#!/usr/bin/env node
// Regenerate the operational root copies from the immutable handoff package, and rewrite
// handoff-provenance.json.
//
// Files listed under `overrides` are NOT overwritten: those are deliberate operational
// corrections authorised by a named ADR (for example the corrected event envelope and agent
// registry). Their recorded hash is refreshed from disk so the drift check pins the reviewed
// content. Everything else is restored byte-for-byte from the handoff.
//
// Run:  pnpm sync:handoff        (then review the diff and commit)

import { copyFileSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import {
  HANDOFF_SOURCE_PATH,
  HANDOFF_VERSION,
  PROVENANCE_FILE,
  REPO_ROOT,
  enumerateHandoffFiles,
  readProvenance,
  sha256,
} from './handoff-sources.mjs';

const previous = existsSync(PROVENANCE_FILE) ? readProvenance() : { overrides: {} };
const overrides = previous.overrides ?? {};

const files = enumerateHandoffFiles();
let copied = 0;
let preserved = 0;

for (const file of files) {
  const destAbs = join(REPO_ROOT, file.destination);
  mkdirSync(dirname(destAbs), { recursive: true });

  if (overrides[file.destination]) {
    if (!existsSync(destAbs)) {
      console.error(
        `error: ${file.destination} is declared as an override but does not exist on disk`,
      );
      process.exit(1);
    }
    overrides[file.destination].sha256 = sha256(destAbs);
    overrides[file.destination].sourceSha256 = file.sourceSha256;
    preserved += 1;
    continue;
  }

  copyFileSync(join(REPO_ROOT, file.source), destAbs);
  copied += 1;
}

const provenance = {
  $comment:
    'Generated by scripts/sync-handoff.mjs. Do not hand-edit hashes. Verified in CI by ' +
    'scripts/check-handoff-provenance.mjs.',
  handoffVersion: HANDOFF_VERSION,
  handoffSource: HANDOFF_SOURCE_PATH,
  generatedFiles: files,
  overrides,
};

writeFileSync(PROVENANCE_FILE, `${JSON.stringify(provenance, null, 2)}\n`);

console.log(`handoff sync complete`);
console.log(`  copied verbatim : ${copied}`);
console.log(`  overrides kept  : ${preserved}`);
console.log(`  provenance      : handoff-provenance.json`);
